# Generated by Django 5.2.15 on 2026-07-14 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_jobseekerprofile_resume_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEmbedding',
            fields=[
                ('embedding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills_embedding', models.JSONField(default=list)),
                ('experience_embedding', models.JSONField(default=list)),
                ('education_embedding', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='profiles.jobseekerprofile')),
            ],
        ),
    ]
